"""Add user relationship to Reservation

Revision ID: 73f60284f1a4
Revises: 5a18f4821ab5
Create Date: 2023-09-04 12:57:34.128956

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '73f60284f1a4'
down_revision = '5a18f4821ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_donation_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
