"""Add invested_amount in charityproject

Revision ID: cb84f5de70e2
Revises: d3e71ad47769
Create Date: 2023-08-31 11:04:31.956094

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'cb84f5de70e2'
down_revision = 'd3e71ad47769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('invested_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'invested_amount')
    # ### end Alembic commands ###
