"""Added fields charityproject

Revision ID: d3e71ad47769
Revises: 379a3d619123
Create Date: 2023-08-30 15:47:31.691521

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd3e71ad47769'
down_revision = '379a3d619123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('charityproject', sa.Column('full_amount', sa.Integer(), nullable=False))
    op.add_column('charityproject', sa.Column('fully_invested', sa.Boolean(), nullable=True))
    op.add_column('charityproject', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('charityproject', sa.Column('close_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_charityproject_create_date'), 'charityproject', ['create_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charityproject_create_date'), table_name='charityproject')
    op.drop_column('charityproject', 'close_date')
    op.drop_column('charityproject', 'create_date')
    op.drop_column('charityproject', 'fully_invested')
    op.drop_column('charityproject', 'full_amount')
    op.drop_column('charityproject', 'description')
    # ### end Alembic commands ###
